name: secondapp
description: "A new Flutter project mainly focusing on user inputs"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
awesome_dialog: ^3.0.2
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/apple.png
    - assets/login.jpg
    - assets/register.jpg
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png