name: secondapp
description: "A new Flutter project mainly focusing on user inputs"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
awesome_dialog: ^3.0.2
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/apple.png
    - assets/login.jpg
    - assets/register.jpg
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/bird.png
    - assets/images/bunny.png
    - assets/images/cat.png
    - assets/images/dog.png
    - assets/images/dog0.png
    - assets/images/dog1.png
    - assets/images/dog2.png
    - assets/images/dog3.png
    - assets/images/dog4.png
    - assets/images/dog5.png
    - assets/images/dog6.png
    - assets/images/dog7.png
    - assets/images/dog8.png
    - assets/images/dog9.png
    - assets/images/horse.png
    - assets/images/profile.jpg
    - assets/images/s1.jpg
    - assets/images/s2.jpg
    - assets/images/s3.jpg
    - assets/images/s4.jpg
    - assets/images/doog.png
    - assets/images/doberman.png
    - assets/images/dobe.png
    - assets/images/beagle.webp
    - assets/images/beagle1.png
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularAir-Medium.ttf
        - asset: assets/fonts/CircularAir-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularAir-Light.ttf


